name: HashServer

on: [push,pull_request, issues]

jobs:
  testRelease:
    name: Start Server
    runs-on: windows-latest
    
    steps:
      - name: Run Server
        shell: cmd
        working-directory: .\master
        run: startserver.cmd
      - name: Run Post Request
        shell: cmd
        working-directory: .\master
        run: call .\postrequest.cmd
      - name: Run Get Request
        shell: cmd
        working-directory: .\master
        run: call .\getrequest.cmd
      - name: Run Stat Request
        shell: cmd
        working-directory: .\master
        run: call .\getstat.cmd
      - name: Run Multiple Post Request
        shell: cmd 
        working-directory: .\master
        run: call .\multiple.cmd
      - name: Run Shutdown Request
        shell: cmd
        working-directory: .\master
        run: call .\shutdown.cmd
        
 
