name: HashServer

on: [push,pull_request, issues]

jobs:
  testRelease:
    name: Hash Server Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Start Server
        shell: bash
        working-directory: .\master
        run: startserver.sh
      - name: Run Post Request
        shell: bash
        working-directory: .\master
        run: call .\postrequest.sh
      - name: Run Get Request
        shell: bash
        working-directory: .\master
        run: call .\getrequest.sh
      - name: Run Stats Request
        shell: bash
        working-directory: .\master
        run: call .\getstat.sh
      - name: Run Multiple Post Request
        shell: bash
        working-directory: .\master
        run: call .\multiplerequest.sh
      - name: Run Shutdown Request
        shell: bash
        working-directory: .\master
        run: call .\shutdown.sh
        
 
