name: HashServer

on: [push,pull_request, issues]

jobs:
  testRelease:
    name: Hash Server Testing
    runs-on: ubuntu-latest
    
    steps:
      - name: Start Server
        shell: bash
        run: ./startserver.sh
      - name: Run Post Request
        shell: bash
        run: ./postrequest.sh
      - name: Run Get Request
        shell: bash
        run: ./getrequest.sh
      - name: Run Stats Request
        shell: bash
        run: ./getstat.sh
      - name: Run Multiple Post Request
        shell: bash
        run: ./multiplerequest.sh
      - name: Run Shutdown Request
        shell: bash
        run: ./shutdown.sh
        
 
