name: HashServer

on: 
  push:
    branches:
        - master

jobs:
  testRelease:
    name: Hash Server Testing
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Start Server
      env: 
          PORT: 8088
      shell: bash
      run:
            ls -la
            chmod +x ./startserver.sh
            ./startserver.sh
            
    - name: Run Post Request
      shell: bash  
      run:
        chmod +x ./postrequest.sh
        ./postrequest.sh
        
    - name: Run Get Request
      shell: bash
      run: 
        chmod +x ./getrequest.sh
        ./getrequest.sh
   
    - name: Run stats Request
      shell: bash
      run: 
        chmod +x ./getstat.sh
        ./getstat.sh
        
    - name: Run Multiple POST Request
      shell: bash
      run: 
        chmod +x ./multiplerequest.sh
        ./multiplerequest.sh

    - name: Run Shutdown Request
      shell: bash
      run: 
        chmod +x ./shutdown.sh
        ./shutdown.sh
        
 
